(()=>{
 const root=document.getElementById('gi-beta'),$=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=c=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),num=n=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
 const now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-'),currentMonth=today.slice(0,7);
 let db={version:1,entries:[],goals:[]},revision=0,ready=false,demo=false,busy=false,view='dashboard',page=0,pendingRestore=null,confirmAction=null;
 const requests=new Map();let seq=0;
 function request(op,payload){return new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{requests.delete(id);reject(Error('Não foi possível confirmar a operação. Recarregue e confira os dados antes de tentar novamente.'));},60000);requests.set(id,{resolve,reject,timer});parent.postMessage({type:'gi-beta-request',id,op,payload},'*');});}
 window.addEventListener('message',e=>{if(e.source!==parent)return;const m=e.data;if(m?.type==='gi-beta-result'){const r=requests.get(m.id);if(!r)return;clearTimeout(r.timer);requests.delete(m.id);m.ok?r.resolve(m):r.reject(Error(m.error||'Não foi possível salvar.'));}if(m?.type==='gi-beta-changed'){ready=false;notice('Os dados foram alterados em outra aba. Recarregue esta página antes de continuar para evitar sobrescrever alterações.');}});
 const notify=t=>{$('#toast').textContent=t;};const notice=t=>{$('#notice').textContent=t;$('#notice').hidden=!t;};
 function amount(s){const v=s.trim();if(!/^(?:\d+|\d{1,3}(?:\.\d{3})+)(?:,\d{1,2})?$/.test(v))throw Error('Use um valor como 1.250,50, sem R$.');const [a,b='']=v.replaceAll('.','').split(',');const c=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(c)||c>100000000000)throw Error('Valor acima do limite da beta.');return c;}
 const amountInput=c=>(c/100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
 const normal=s=>s.trim().replace(/\s+/g,' ');const same=(a,b)=>a.localeCompare(b,'pt-BR',{sensitivity:'accent'})===0;
 function canonical(value,existing){const n=normal(value);return existing.find(x=>same(x,n))||n;}
 const clone=()=>structuredClone(db);
 function sample(){return {version:1,goals:[{month:currentMonth,store:'Loja exemplo',cents:12800000}],entries:[{id:'demo1',date:currentMonth+'-01',store:'Loja exemplo',seller:'Ana Beatriz',cents:3825019,orders:350,pieces:790},{id:'demo2',date:currentMonth+'-02',store:'Loja exemplo',seller:'Carla Souza',cents:3650000,orders:340,pieces:770},{id:'demo3',date:currentMonth+'-03',store:'Loja exemplo',seller:'Juliana Lima',cents:3360000,orders:319,pieces:720}]};}
 const data=()=>demo?sample():db;
 function filtered(){return data().entries.filter(e=>e.date.startsWith($('#month').value)&&(!$('#store').value||e.store===$('#store').value));}
 function options(){const d=data(),a=validateDB(d).admin,selected=$('#store').value,stores=[...new Set([...d.entries,...d.goals].map(e=>e.store).concat(a.stores.filter(x=>x.active).map(x=>x.name)))].sort();$('#store').innerHTML='<option value="">Todas as lojas</option>'+stores.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('#store').value=stores.includes(selected)?selected:'';$('#stores-list').innerHTML=a.stores.filter(x=>x.active).map(x=>x.name).map(s=>`<option value="${esc(s)}"></option>`).join('');$('#sellers-list').innerHTML=[...new Set(a.sellers.filter(x=>x.active&&a.stores.some(t=>t.id===x.storeId&&t.active)).map(x=>x.name))].map(s=>`<option value="${esc(s)}"></option>`).join('');}
 function show(v){if(cloudProfile&&((cloudProfile.role==='seller'&&!['evolution','backup'].includes(v))||(cloudProfile.role!=='admin'&&v==='admin')))v='evolution';if(v==='admin'&&demo){demo=false;notify('De volta aos seus dados online.');render();}view=v;$('.filters').hidden=v==='admin';$('#new-entry').hidden=v==='admin'||v==='evolution';all('.view').forEach(e=>e.hidden=e.id!==v);all('nav [data-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.view===v?'page':'false'));const titles={admin:['Sua operação, organizada.','Gerencie cadastros, perfis e alterações.'],evolution:['Evolução da equipe','Compare resultados e acompanhe cada vendedor.'],dashboard:['Visão geral da operação','Acompanhe lojas, equipes e pontos de atenção.'],records:['Cada lançamento conta.','Registre, revise e acompanhe suas vendas.'],targets:['Um objetivo claro para o mês.','Defina as metas de cada loja.'],backup:['Seus dados, sempre por perto.','Guarde uma cópia e restaure quando precisar.']};$('#page-title').textContent=titles[v][0];$('#page-sub').textContent=titles[v][1];if(v==='evolution')renderEvolution();if(window.matchMedia('(max-width:760px), (max-width:1000px) and (max-height:500px)').matches)window.scrollTo(0,0);}
 function state(percent,month,hasGoal,hasData){if(!hasGoal)return {label:'Sem meta',color:'#6B7280',bg:'#F3F4F6'};if(!hasData)return {label:'Sem dados',color:'#6B7280',bg:'#F3F4F6'};if(month>currentMonth)return {label:'Período futuro',color:'#6B7280',bg:'#F3F4F6'};return percent<50?{label:'Urgente',color:'#EF4444',bg:'#FEE2E2'}:percent<80?{label:'Atenção',color:'#F59E0B',bg:'#FEF3C7'}:{label:'Bom resultado',color:'#10B981',bg:'#D1FAE5'};}
 function render(){
  options();const rows=filtered(),d=data(),month=$('#month').value,store=$('#store').value;
  const goals=d.goals.filter(g=>g.month===month&&(!store||g.store===store)),sales=rows.reduce((s,e)=>s+e.cents,0),orders=rows.reduce((s,e)=>s+e.orders,0),pieces=rows.reduce((s,e)=>s+e.pieces,0),goal=goals.reduce((s,g)=>s+g.cents,0);
  const uncovered=rows.some(e=>!goals.some(g=>g.store===e.store)),hasGoal=goal>0&&!uncovered,percent=hasGoal?sales/goal*100:0,status=state(percent,month,hasGoal,rows.length>0);
  $('#empty').hidden=rows.length>0||goals.length>0;$('#k-goal').textContent=goal?money(goal):'—';$('#goal-context').textContent=uncovered?'Há loja com vendas sem meta':goals.length?`${goals.length} loja(s) com meta`:'Cadastre uma meta';$('#k-sales').textContent=money(sales);$('#orders-context').textContent=`${num(orders)} atendimentos · ${num(pieces)} peças`;$('#k-ticket').textContent=orders?money(Math.round(sales/orders)):'—';$('#k-pa').textContent=orders?num(pieces/orders):'—';
  $('#result-badge').innerHTML=`<i class="dot" style="background:${status.color}"></i>${status.label}`;$('#result-badge').style.background=status.bg;
  const gaugeText=hasGoal&&rows.length?num(percent)+'%':'—';$('#gauge-value').textContent=gaugeText;$('#gauge').setAttribute('aria-label',`${gaugeText} da meta mensal. ${status.label}`);for(const id of ['#gauge-progress','#gauge-outline']){$(id).setAttribute('stroke-dasharray',`${hasGoal&&rows.length?Math.min(100,Math.max(0,percent)):0} 100`);}$('#gauge-progress').setAttribute('stroke',status.color);
  $('#gap-label').textContent=hasGoal&&sales>goal?'Acima da meta':'Falta para a meta';$('#gap-value').textContent=hasGoal?money(Math.abs(goal-sales)):'—';$('#period-note').textContent=uncovered?'Cadastre metas para todas as lojas com vendas antes de comparar o total.':month>=currentMonth?'Percentual acumulado da meta mensal. Período ainda em andamento.':rows.length?'Mês encerrado · classificação pelas faixas propostas.':'Registre resultados para avaliar o período.';
  const sellers=new Map();rows.forEach(e=>{const a=sellers.get(e.seller)||{cents:0,orders:0,pieces:0};a.cents+=e.cents;a.orders+=e.orders;a.pieces+=e.pieces;sellers.set(e.seller,a);});
  $('#team-body').innerHTML=sellers.size?[...sellers].sort((a,b)=>b[1].cents-a[1].cents).map(([name,e])=>`<tr><td>${esc(name)}</td><td data-label="Vendas">${money(e.cents)}</td><td data-label="Atendimentos">${num(e.orders)}</td><td data-label="Peças">${num(e.pieces)}</td><td data-label="TM">${e.orders?money(Math.round(e.cents/e.orders)):'—'}</td><td data-label="PA">${e.orders?num(e.pieces/e.orders):'—'}</td></tr>`).join(''):'<tr><td colspan="6">Nenhum lançamento neste período.</td></tr>';
  const weekly=[0,0,0,0,0];rows.forEach(e=>weekly[Math.min(4,Math.floor((Number(e.date.slice(-2))-1)/7))]+=e.cents);$('#weeks').innerHTML=weekly.map((v,i)=>`<div class="week"><div><span>Dias ${i*7+1}–${Math.min((i+1)*7,new Date(Number(month.slice(0,4)),Number(month.slice(-2)),0).getDate())}</span><strong>${money(v)}</strong></div><div class="track"><span style="width:${sales?v/sales*100:0}%;background:#059669"></span></div></div>`).filter((_,i)=>i*7<new Date(Number(month.slice(0,4)),Number(month.slice(-2)),0).getDate()).join('');
  chart(rows,month,status);renderHistory(rows);renderGoals();$('#storage-status').textContent=demo?'Exemplo · não salvo':ready?'Salvamento local ativo':'Armazenamento indisponível';$('#demo').textContent=demo?'Voltar aos meus dados':'Ver exemplo';$('#footer-mode').textContent=demo?'Dados fictícios · modo de exemplo':'Beta local · sem envio de dados ao servidor';$('#backup-count').textContent=`${db.entries.length} lançamento(s) e ${db.goals.length} meta(s), ${adminState().stores.length} loja(s) e ${adminState().users.length} usuário(s) e ${adminState().sellerGoals.length} meta(s) individual(is) no backup.`;renderAdmin();renderOperation();renderEvolution();renderSellerGoals();renderCloudUI();
 }
 function chart(rows,month,status){
  $('#chart-label').textContent=rows.length?'Vendas acumuladas':'Sem dados';const days=new Date(Number(month.slice(0,4)),Number(month.slice(-2)),0).getDate(),daily=Array(days).fill(0);rows.forEach(e=>daily[Number(e.date.slice(-2))-1]+=e.cents);let sum=0;const values=daily.map(v=>(sum+=v));const w=Math.max(240,$('#chart').clientWidth-36),h=230,left=65,right=20,top=20,bottom=35,max=Math.max(100,...values)*1.12,x=i=>left+i*(w-left-right)/(days-1),y=v=>h-bottom-v/max*(h-top-bottom),points=values.map((v,i)=>`${x(i)},${y(v)}`).join(' '),color='#059669';
  $('#chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="group" aria-label="Vendas acumuladas por dia"><defs><linearGradient id="beta-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${color}" stop-opacity=".2"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${[0,.5,1].map(t=>`<line x1="${left}" x2="${w-right}" y1="${y(max*t)}" y2="${y(max*t)}" stroke="#E5E7EB" stroke-dasharray="3 5"/><text x="${left-7}" y="${y(max*t)+4}" text-anchor="end">${num(Math.round(max*t/100))}</text>`).join('')}<text x="${left}" y="12">R$</text><polygon points="${left},${h-bottom} ${points} ${w-right},${h-bottom}" fill="url(#beta-fill)"/><polyline points="${points}" fill="none" stroke="${color}" stroke-width="2.5"/>${[0,6,13,20,days-1].map(i=>`<text x="${x(i)}" y="${h-10}" text-anchor="middle">${String(i+1).padStart(2,'0')}</text>`).join('')}${daily.map((v,i)=>v||rows.some(e=>Number(e.date.slice(-2))===i+1)?`<g class="chart-point" tabindex="0" role="button" data-day="${i}" aria-label="Dia ${i+1}, vendas ${money(v)}, acumulado ${money(values[i])}"><circle class="point-ring" cx="${x(i)}" cy="${y(values[i])}" r="10" fill="transparent"/><circle cx="${x(i)}" cy="${y(values[i])}" r="4" fill="${color}" stroke="#FFFFFF"/></g>`:'').join('')}</svg>`;
  $('#chart-detail').textContent=rows.length?'Passe o mouse, toque ou use Tab nos pontos para ver os valores.':'Os resultados aparecerão após o primeiro lançamento.';
  all('[data-day]').forEach(el=>{const detail=()=>{$('#chart-detail').textContent=el.getAttribute('aria-label');};el.addEventListener('pointerenter',detail);el.addEventListener('focus',detail);el.addEventListener('click',detail);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detail();}});});
 }
 function renderHistory(rows){const sorted=[...rows].sort((a,b)=>b.date.localeCompare(a.date)||a.seller.localeCompare(b.seller)),pages=Math.max(1,Math.ceil(sorted.length/8));page=Math.min(page,pages-1);$('#history').innerHTML=sorted.slice(page*8,page*8+8).map(e=>`<div class="history-row"><div><strong>${esc(e.seller)} · ${money(e.cents)}</strong><small>${e.date.split('-').reverse().join('/')} · ${esc(e.store)}</small><small>${e.orders} atendimentos · ${e.pieces} peças</small></div><div class="history-actions"><button data-edit="${e.id}">Editar</button><button data-delete="${e.id}">Excluir</button></div></div>`).join('')||'<p>Nenhum lançamento neste período.</p>';$('#page-count').textContent=`${page+1} de ${pages}`;$('#previous').disabled=page===0;$('#next').disabled=page>=pages-1;}
 function renderGoals(){$('#goals-list').innerHTML=data().goals.filter(g=>g.month===$('#month').value).map(g=>`<div class="goal-row"><div><strong>${esc(g.store)}</strong><small>${money(g.cents)} · ${g.month}</small></div><button data-goal="${esc(g.store)}">Editar</button></div>`).join('')||'<p>Nenhuma meta para este mês.</p>';}
 async function save(next,action='Atualizou dados'){if(demo)throw Error('Você está no exemplo. Volte aos seus dados para salvar.');if(!ready)throw Error('Armazenamento indisponível. Recarregue a página e confira as permissões do navegador.');if(busy)throw Error('Aguarde o salvamento em andamento.');next=validateDB(next);next.admin.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),actor:'Operador local',action});next.admin.audit=next.admin.audit.slice(-200);validateDB(next);busy=true;try{const result=await request('save',{revision,data:next});acceptCloud(result);$('#saved-at').textContent='Confirmado no Supabase às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});render();}finally{busy=false;}}
 function resetEntry(){$('#entry-form').reset();$('#entry-id').value='';$('#entry-date').value=today;$('#entry-title').textContent='Novo lançamento';$('#cancel-edit').hidden=true;$('#entry-error').textContent='';}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)show(b.dataset.view);if(b.dataset.edit){const r=data().entries.find(x=>x.id===b.dataset.edit);if(!r)return;$('#entry-id').value=r.id;$('#entry-date').value=r.date;$('#entry-store').value=r.store;$('#entry-seller').value=r.seller;$('#entry-sales').value=amountInput(r.cents);$('#entry-orders').value=r.orders;$('#entry-pieces').value=r.pieces;$('#entry-title').textContent='Editar lançamento';$('#cancel-edit').hidden=false;$('#entry-date').focus();}if(b.dataset.delete){const r=data().entries.find(x=>x.id===b.dataset.delete);$('#confirm-text').textContent=`${r.seller} · ${money(r.cents)} · ${r.date.split('-').reverse().join('/')}. Esta ação exclui o lançamento do banco e registra a alteração no histórico.`;confirmAction=async()=>{const next=clone();next.entries=next.entries.filter(x=>x.id!==r.id);await save(next,'Excluiu resultado de '+r.seller);notify('Lançamento excluído.');};$('#confirm-dialog').showModal();}if(b.dataset.goal){const g=data().goals.find(x=>x.month===$('#month').value&&x.store===b.dataset.goal);$('#goal-month').value=g.month;$('#goal-store').value=g.store;$('#goal-value').value=amountInput(g.cents);$('#goal-value').focus();}});
 $('#confirm-no').onclick=()=>$('#confirm-dialog').close();$('#confirm-yes').onclick=async()=>{try{await confirmAction();$('#confirm-dialog').close();}catch(e){$('#confirm-dialog').close();notice(e.message);}};
 $('#new-entry').onclick=()=>{show('records');resetEntry();$('#entry-date').focus();};$('#cancel-edit').onclick=resetEntry;
 $('#entry-form').onsubmit=async e=>{e.preventDefault();$('#entry-error').textContent='';try{const next=clone(),registry=adminState(),id=$('#entry-id').value||crypto.randomUUID(),store=canonical($('#entry-store').value,[...next.entries,...next.goals].map(x=>x.store).concat(registry.stores.map(x=>x.name))),seller=canonical($('#entry-seller').value,next.entries.filter(x=>same(x.store,store)).map(x=>x.seller).concat(registry.sellers.filter(x=>registry.stores.some(t=>t.id===x.storeId&&same(t.name,store))).map(x=>x.name))),record={id,updatedAt:new Date().toISOString(),date:$('#entry-date').value,store,seller,cents:amount($('#entry-sales').value),orders:Number($('#entry-orders').value),pieces:Number($('#entry-pieces').value)};if(!$('#entry-id').value){const a=adminState(),st=a.stores.find(x=>same(x.name,record.store));if(st&&!st.active)throw Error('Esta loja está arquivada. Reative o cadastro na Administração.');if(st&&a.sellers.some(x=>x.storeId===st.id&&same(x.name,record.seller)&&!x.active))throw Error('Este vendedor está arquivado. Reative o cadastro na Administração.');}if(record.date>today)throw Error('O lançamento não pode ter uma data futura.');if(record.orders===0&&(record.cents>0||record.pieces>0))throw Error('Informe ao menos um atendimento para vendas ou peças registradas.');if(next.entries.some(x=>x.id!==id&&x.date===record.date&&same(x.store,store)&&same(x.seller,seller)))throw Error('Já existe um lançamento deste vendedor, loja e dia. Edite o registro no histórico para evitar duplicidade.');const index=next.entries.findIndex(x=>x.id===id);if(index<0)next.entries.push(record);else next.entries[index]=record;await save(next,(index<0?'Registrou':'Editou')+' resultado de '+record.seller);$('#month').value=record.date.slice(0,7);$('#store').value=record.store;page=0;render();resetEntry();notify('Lançamento salvo. Indicadores atualizados.');}catch(error){$('#entry-error').textContent=error.message;}};
 $('#goal-form').onsubmit=async e=>{e.preventDefault();$('#goal-error').textContent='';try{const next=clone(),registry=adminState(),g={month:$('#goal-month').value,store:canonical($('#goal-store').value,[...next.entries,...next.goals].map(x=>x.store).concat(registry.stores.map(x=>x.name))),cents:amount($('#goal-value').value)};if(adminState().stores.some(x=>same(x.name,g.store)&&!x.active))throw Error('Esta loja está arquivada. Reative o cadastro na Administração.');if(g.cents<=0)throw Error('A meta deve ser maior que zero.');const index=next.goals.findIndex(x=>x.month===g.month&&same(x.store,g.store));if(index<0)next.goals.push(g);else next.goals[index]=g;await save(next,(index<0?'Cadastrou':'Editou')+' meta de '+g.store);$('#month').value=g.month;render();notify('Meta salva. Indicadores atualizados.');}catch(error){$('#goal-error').textContent=error.message;}};
 $('#month').value=currentMonth;$('#goal-month').value=currentMonth;$('#month').onchange=()=>{if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test($('#month').value))$('#month').value=currentMonth;page=0;render();};$('#store').onchange=()=>{page=0;render();};$('#previous').onclick=()=>{page--;renderHistory(filtered());};$('#next').onclick=()=>{page++;renderHistory(filtered());};
 $('#demo').onclick=()=>{demo=!demo;$('#month').value=currentMonth;$('#store').value='';page=0;resetEntry();render();notify(demo?'Explorando dados fictícios. Seus dados permanecem guardados.':'De volta aos seus dados.');};
 $('#export').onclick=async()=>{try{if(demo)throw Error('Saia do exemplo para exportar seus dados.');acceptCloud(await request('export'));render();notify('Backup preparado. Confira o arquivo na pasta de downloads.');}catch(e){notice(e.message);}};
 $('#restore-file').onchange=async e=>{pendingRestore=null;$('#restore-preview').hidden=true;$('#restore-error').textContent='';try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Arquivo maior que o limite de 2 MB.');pendingRestore=validateDB(JSON.parse(await file.text()));$('#restore-summary').textContent=`Este backup contém ${pendingRestore.entries.length} lançamento(s) e ${pendingRestore.goals.length} meta(s), ${pendingRestore.admin.stores.length} loja(s), ${pendingRestore.admin.sellers.length} vendedor(es) e ${pendingRestore.admin.users.length} usuário(s) e ${pendingRestore.admin.sellerGoals.length} meta(s) individual(is). Os cadastros administrativos também serão substituídos. Ao confirmar, os ${db.entries.length} lançamento(s) e ${db.goals.length} meta(s) atuais serão substituídos. Baixe um backup antes se quiser preservá-los.`;$('#restore-preview').hidden=false;}catch(error){$('#restore-error').textContent=error instanceof SyntaxError?'O arquivo não contém JSON válido.':error.message;}};
 $('#restore-cancel').onclick=()=>{pendingRestore=null;$('#restore-preview').hidden=true;$('#restore-file').value='';};$('#restore-confirm').onclick=async()=>{try{throw Error('A restauração local está desativada no modo online. Seus backups continuam preservados.');if(!pendingRestore)return;await save(pendingRestore,'Restaurou backup');$('#restore-cancel').click();resetEntry();notify('Backup restaurado e salvo neste navegador.');}catch(e){$('#restore-error').textContent=e.message;}};
 // Handle local forms without requesting sandbox form-navigation privileges.
 for(const id of ['#entry-form','#goal-form']){const form=$(id);const submit=e=>{e.preventDefault();if(form.reportValidity())form.onsubmit(e);};form.querySelector('button[type=submit]').addEventListener('click',submit);form.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT')submit(e);});}
 let chartWidth=0;new ResizeObserver(()=>{const width=$('#chart').clientWidth;if(width>0&&width!==chartWidth){chartWidth=width;render();}}).observe($('#chart'));
 // CLOUD_MODULE
 // ADMIN_MODULE
 // EVOLUTION_MODULE
 resetEntry();render();show('dashboard');request('read').then(result=>{acceptCloud(result);ready=true;render();if(cloudProfile.role==='seller')show('evolution');}).catch(e=>{notice(e.message);render();});
})();
