(()=>{
 const root=document.getElementById('gi-beta'),$=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 let indicatorAnimation=0;
 const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
 function animateIndicators(){
  if(!animationIntent)return;if(reduceMotion.matches||(!ready&&!demo)){animationIntent=false;return;}
  const scope=view==='dashboard'?$('#dashboard'):view==='evolution'?$('#evolution'):view==='targets'?$('#targets'):null;if(!scope||scope.hidden){animationIntent=false;return;}
  const animation=++indicatorAnimation;
  const count=(el,target,format,duration=1200)=>{if(!Number.isFinite(target)){el.textContent='—';return;}el.dataset.countFinal=el.textContent;const start=performance.now();const step=now=>{if(!el.isConnected||animation!==indicatorAnimation)return;const p=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-p,3);el.textContent=format(target*ease);if(p<1&&!reduceMotion.matches)requestAnimationFrame(step);else el.textContent=format(target);};el.textContent=format(0);requestAnimationFrame(step);};
  if(view==='dashboard'){
   const sales=Number(($('#k-sales').dataset.countFinal||$('#k-sales').textContent).replace(/[^0-9,.-]/g,'').replaceAll('.','').replace(',','.'));
   const finalSales=$('#k-sales').dataset.countFinal||$('#k-sales').textContent;
   if(Number.isFinite(sales)){const fmt=v=>(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});$('#k-sales').setAttribute('aria-label',finalSales);count($('#k-sales'),sales*100,fmt);}
   const gauge=Number(($('#gauge-value').dataset.countFinal||$('#gauge-value').textContent).replace('%','').replace('.','').replace(',','.'));
   if(Number.isFinite(gauge)){const final=$('#gauge-value').textContent;$('#gauge-value').setAttribute('aria-label',final);$('#gauge-value').setAttribute('aria-live','off');count($('#gauge-value'),gauge,v=>num(v)+'%');}
   const progress=$('#sales-progress'),width=progress.style.width,goalCents=Number($('#k-goal').textContent.replace(/[^0-9,.-]/g,'').replaceAll('.','').replace(',','.'))*100,targetPct=Number.isFinite(goalCents)&&goalCents>0?sales*10000/goalCents:0,finalColor=$('#gauge-progress').getAttribute('stroke'),start=performance.now();progress.style.width='0%';progress.style.background=goalCents>0?statusFor(0).color:finalColor;requestAnimationFrame(()=>{progress.style.width=width;});const colorTick=now=>{if(animation!==indicatorAnimation)return;const p=Math.min(1,(now-start)/1200),pct=targetPct*(1-Math.pow(1-p,3)),color=goalCents>0&&width!=='0%'?statusFor(pct).color:finalColor;progress.style.background=color;$('#gauge-progress').setAttribute('stroke',color);if(p<1&&!reduceMotion.matches)requestAnimationFrame(colorTick);};requestAnimationFrame(colorTick);
   const bars=[...scope.querySelectorAll('.week .track span,.goal-metrics .track span,.team .track span,.operation-grid .track span')];bars.forEach((bar,i)=>{const final=bar.style.width;bar.style.setProperty('--stagger-index',i);bar.style.width='0%';requestAnimationFrame(()=>{bar.style.width=final;});});
  }else if(view==='evolution'){
   const sales=scope.querySelector('.seller-sales>strong');if(sales){const value=Number(sales.textContent.replace(/[^0-9,.-]/g,'').replaceAll('.','').replace(',','.'));if(Number.isFinite(value)){const final=sales.textContent;sales.setAttribute('aria-label',final);count(sales,value*100,v=>(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}));}}
   const bars=[...scope.querySelectorAll('#evo-goal-bar,.seller-card .track span')];bars.forEach((bar,i)=>{const final=bar.style.width;bar.style.setProperty('--stagger-index',i);bar.style.width='0%';requestAnimationFrame(()=>{bar.style.width=final;});});
  }
  if(view==='targets'){scope.querySelectorAll('.goal-metrics .track span').forEach((bar,i)=>{const final=bar.style.width;bar.style.setProperty('--stagger-index',Math.min(i,10));bar.style.width='0%';requestAnimationFrame(()=>bar.style.width=final);});}
  scope.querySelectorAll('.chart-line').forEach(line=>{try{const length=line.getTotalLength();line.style.strokeDasharray=`0 ${length}`;requestAnimationFrame(()=>line.style.strokeDasharray=`${length} ${length}`);}catch{}});
  scope.querySelectorAll('.chart-bar').forEach(bar=>{bar.style.transformOrigin='center bottom';bar.style.transform='scaleY(0)';requestAnimationFrame(()=>{bar.style.transitionDelay=`calc(var(--stagger-index,0) * 18ms)`;bar.style.transform='scaleY(1)';});});
  animationIntent=false;
 }
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=c=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),num=n=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
 const now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-'),currentMonth=today.slice(0,7);
 let db={version:1,entries:[],goals:[]},revision=0,ready=false,demo=false,busy=false,view='dashboard',page=0,pendingRestore=null,confirmAction=null,animationIntent=false,recentlySavedId='';
 const requests=new Map();let seq=0;
 function request(op,payload){return new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{requests.delete(id);reject(Error('Não foi possível confirmar a operação. Recarregue e confira os dados antes de tentar novamente.'));},60000);requests.set(id,{resolve,reject,timer});parent.postMessage({type:'gi-beta-request',id,op,payload},'*');});}
 window.addEventListener('message',e=>{if(e.source!==parent)return;const m=e.data;if(m?.type==='gi-beta-result'){const r=requests.get(m.id);if(!r)return;clearTimeout(r.timer);requests.delete(m.id);m.ok?r.resolve(m):r.reject(Error(m.error||'Não foi possível salvar.'));}if(m?.type==='gi-beta-changed'){ready=false;notice('Os dados foram alterados em outra aba. Recarregue esta página antes de continuar para evitar sobrescrever alterações.');}});
 let toastTimer=0;const notify=t=>{const toast=$('#toast');toast.textContent=t;toast.classList.toggle('is-success',/salv[oa]|conta criada|exclu[ií]do/i.test(t));toast.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2300);};const notice=t=>{$('#notice').textContent=t;$('#notice').hidden=!t;};
 function amount(s){const v=s.trim();if(!/^(?:\d+|\d{1,3}(?:\.\d{3})+)(?:,\d{1,2})?$/.test(v))throw Error('Use um valor como 1.250,50, sem R$.');const [a,b='']=v.replaceAll('.','').split(',');const c=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(c)||c>100000000000)throw Error('Valor acima do limite da beta.');return c;}
 const amountInput=c=>(c/100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
 const normal=s=>s.trim().replace(/\s+/g,' ');const same=(a,b)=>a.localeCompare(b,'pt-BR',{sensitivity:'accent'})===0;
 function canonical(value,existing){const n=normal(value);return existing.find(x=>same(x,n))||n;}
 const clone=()=>structuredClone(db);
 function sample(){return {version:1,goals:[{month:currentMonth,store:'Loja exemplo',cents:12800000}],entries:[{id:'demo1',date:currentMonth+'-01',store:'Loja exemplo',seller:'Ana Beatriz',cents:3825019,orders:350,pieces:790},{id:'demo2',date:currentMonth+'-02',store:'Loja exemplo',seller:'Carla Souza',cents:3650000,orders:340,pieces:770},{id:'demo3',date:currentMonth+'-03',store:'Loja exemplo',seller:'Juliana Lima',cents:3360000,orders:319,pieces:720}]};}
 const data=()=>demo?sample():db;
 function filtered(){return data().entries.filter(e=>e.date.startsWith($('#month').value)&&(!$('#store').value||e.store===$('#store').value));}
 function options(){const d=data(),a=validateDB(d).admin,selected=$('#store').value,stores=[...new Set([...d.entries,...d.goals].map(e=>e.store).concat(a.stores.filter(x=>x.active).map(x=>x.name)))].sort();$('#store').innerHTML='<option value="">Todas as lojas</option>'+stores.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('#store').value=stores.includes(selected)?selected:'';$('#stores-list').innerHTML=a.stores.filter(x=>x.active).map(x=>x.name).map(s=>`<option value="${esc(s)}"></option>`).join('');$('#sellers-list').innerHTML=[...new Set(a.sellers.filter(x=>x.active&&a.stores.some(t=>t.id===x.storeId&&t.active)).map(x=>x.name))].map(s=>`<option value="${esc(s)}"></option>`).join('');}
 function show(v){if(v==='backup'){adminTab='backup';v='admin';renderAdmin();}if(cloudProfile&&((cloudProfile.role==='seller'&&!['evolution','backup'].includes(v))||(cloudProfile.role!=='admin'&&v==='admin')))v='evolution';if(v===view)return;if(v==='admin'&&demo){demo=false;notify('De volta aos seus dados online.');render();}view=v;animationIntent=true;$('.filters').hidden=v==='admin';$('.filters').classList.toggle('evolution-filters',v==='evolution');$('#evo-seller-filter').hidden=v!=='evolution';$('#new-entry').hidden=v==='admin'||v==='evolution';all('.view').forEach(e=>e.hidden=e.id!==v);all('nav [data-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.view===v?'page':'false'));const titles={admin:['Organize sua operação.','Gerencie cadastros, perfis e alterações.'],evolution:['Evolução da equipe','Compare resultados e acompanhe cada vendedor.'],dashboard:['Visão geral da operação','Acompanhe lojas, equipes e pontos de atenção.'],records:['Cada lançamento conta.','Registre, revise e acompanhe suas vendas.'],targets:['Um objetivo claro para o mês.','Defina as metas de cada loja.'],backup:['Seus dados, sempre por perto.','Guarde uma cópia e restaure quando precisar.']};$('#page-title').textContent=titles[v][0];$('#page-sub').textContent=titles[v][1];if(v==='evolution')renderEvolution();renderGreeting();redesignSync();animateIndicators();root.dispatchEvent(new CustomEvent('gi-view-changed'));if(window.matchMedia('(max-width:760px), (max-width:1000px) and (max-height:500px)').matches)window.scrollTo(0,0);}
 function statusFor(pct){const key=pct==null||!Number.isFinite(pct)?'neutral':pct<50?'danger':pct<80?'warning':'success';return {key,...{neutral:{label:'Sem meta',color:'#BDBDBB',bg:'#F0F0EE',text:'#171717'},danger:{label:'Crítico',color:'#EF4444',bg:'#FEE2E2',text:'#991B1B'},warning:{label:'Atenção',color:'#F59E0B',bg:'#FEF3C7',text:'#92400E'},success:{label:'Atingida',color:'#10B981',bg:'#D1FAE5',text:'#065F46'}}[key]};}
 function state(percent,month,hasGoal,hasData){const s=statusFor(!hasGoal||!hasData||month>currentMonth?null:percent);return {...s,label:!hasGoal?'Sem meta':!hasData?'Sem dados':month>currentMonth?'Período futuro':s.label};}
 function setChartTooltip(tip,title,value,detail=''){tip.innerHTML=`<span class="tooltip-date">${esc(title)}</span><strong>${esc(value)}</strong>${detail?`<span class="tooltip-detail">${esc(detail)}</span>`:''}`;}
 function statusChip(s){return `<span class="badge" style="background:${s.bg};color:${s.text}"><i class="dot" style="background:${s.color}"></i>${s.label}</span>`;}
 function remainingWorkdays(month){const [year,m]=month.split('-').map(Number),last=new Date(year,m,0).getDate();return Array.from({length:last},(_,i)=>i+1).filter(day=>new Date(year,m-1,day).getDay()!==0&&month+'-'+String(day).padStart(2,'0')>today).length;}
 function render(){
  indicatorAnimation++;all('[data-count-final]').forEach(el=>delete el.dataset.countFinal);
  options();const rows=filtered(),d=data(),month=$('#month').value,store=$('#store').value;
  const goals=d.goals.filter(g=>g.month===month&&(!store||g.store===store)),sales=rows.reduce((s,e)=>s+e.cents,0),orders=rows.reduce((s,e)=>s+e.orders,0),pieces=rows.reduce((s,e)=>s+e.pieces,0),goal=goals.reduce((s,g)=>s+g.cents,0);
  const uncovered=rows.some(e=>!goals.some(g=>g.store===e.store)),hasGoal=goal>0&&!uncovered,percent=hasGoal?sales/goal*100:0,status=state(percent,month,hasGoal,rows.length>0);
  $('#empty').hidden=rows.length>0||goals.length>0;$('#k-goal').textContent=goal?money(goal):'—';$('#goal-context').textContent=uncovered?'Há loja com vendas sem meta':goals.length?`${goals.length} loja(s) com meta`:'Cadastre uma meta';$('#k-sales').textContent=money(sales);$('#orders-context').textContent=`${num(orders)} atendimentos · ${num(pieces)} peças`;$('#k-ticket').textContent=orders?money(Math.round(sales/orders)):'—';$('#k-pa').textContent=orders?num(pieces/orders):'—';
  $('#result-badge').innerHTML=`<i class="dot" style="background:${status.color}"></i>${status.label}`;$('#result-badge').style.background=status.bg;$('#result-badge').style.color=status.text;
  const gaugeText=hasGoal&&rows.length?num(percent)+'%':'—';$('#gauge-value').textContent=gaugeText;$('#gauge').setAttribute('aria-label',`${gaugeText} da meta mensal. ${status.label}`);const gaugePercent=hasGoal&&rows.length?Math.min(100,Math.max(0,percent)):0;$('#gauge-progress').setAttribute('stroke-dasharray',`${animationIntent&&!reduceMotion.matches?0:gaugePercent} ${100-(animationIntent&&!reduceMotion.matches?0:gaugePercent)}`);$('#gauge-progress').setAttribute('stroke',status.color);if(animationIntent&&!reduceMotion.matches)requestAnimationFrame(()=>$('#gauge-progress').setAttribute('stroke-dasharray',`${gaugePercent} ${100-gaugePercent}`));
  $('#gap-label').textContent=hasGoal&&sales>goal?'Acima da meta':'Falta para a meta';$('#gap-value').textContent=hasGoal?money(Math.abs(goal-sales)):'—';$('#period-note').textContent=uncovered?'Cadastre metas para todas as lojas com vendas antes de comparar o total.':month>=currentMonth?'Percentual acumulado da meta mensal. Período ainda em andamento.':rows.length?'Mês encerrado · classificação pelas faixas propostas.':'Registre resultados para avaliar o período.';
  const sellers=new Map();rows.forEach(e=>{const a=sellers.get(e.seller)||{cents:0,orders:0,pieces:0};a.cents+=e.cents;a.orders+=e.orders;a.pieces+=e.pieces;sellers.set(e.seller,a);});
  const comparison=evolutionPeriod(month,today),prior=d.entries.filter(e=>e.date.startsWith(comparison.previous)&&Number(e.date.slice(-2))<=comparison.previousCutoff&&(!store||e.store===store));
  const trendBadge=name=>{const before=prior.filter(e=>same(e.seller,name)),current=rows.filter(e=>same(e.seller,name)&&Number((e.periodStart||e.date).slice(-2))<=comparison.cutoff).reduce((sum,e)=>sum+e.cents,0),old=before.reduce((sum,e)=>sum+e.cents,0),trend=salesTrend(current,old,!comparison.future&&before.length>0),symbol=trend.direction==='up'?'▲':trend.direction==='down'?'▼':'—',description=trend.reason+(trend.percent!==null&&trend.percent!==0?' ('+(trend.percent>0?'+':'')+num(trend.percent)+'%)':'')+' · anterior '+money(old);return `<span class="sales-trend ${trend.direction}" role="img" aria-label="${esc(description)}" title="${esc(description)}">${symbol}</span>`;};
  $('#team-trend-note').textContent=month===currentMonth?`Setas: dias 1–${comparison.cutoff} comparados aos dias 1–${comparison.previousCutoff} de ${comparison.previous}.`:`Setas: comparação com ${comparison.previous}. Sem histórico: —.`;
  const registry=evoData();
  $('#team-body').innerHTML=sellers.size?[...sellers].sort((a,b)=>b[1].cents-a[1].cents).map(([name,e])=>{const matches=registry.admin.sellers.filter(s=>same(s.name,name)&&registry.admin.stores.some(st=>st.id===s.storeId&&(!store||same(st.name,store))));const gs=registry.admin.sellerGoals.filter(g=>g.month===month&&matches.some(s=>s.id===g.sellerId)),target=gs.reduce((a,g)=>a+g.cents,0),pct=target?e.cents/target*100:null,st=statusFor(pct);return `<tr><td>${esc(name)}<small>${num(e.orders)} atend. · ${num(e.pieces)} peças</small></td><td data-label="Vendas"><span class="sales-with-trend">${money(e.cents)}${trendBadge(name)}</span></td><td data-label="Atingimento">${target?`<small>meta ${money(target)} · ${num(pct)}%</small><div class="track"><span style="width:${Math.max(0,Math.min(100,pct))}%;background:${st.color}"></span></div>`:'—'}</td><td data-label="Status">${statusChip(st)}</td><td data-label="TM">${e.orders?money(Math.round(e.cents/e.orders)):'—'}</td><td data-label="PA">${e.orders?num(e.pieces/e.orders):'—'}</td></tr>`;}).join(''):'<tr><td colspan="6">Nenhum lançamento neste período.</td></tr>';
  const weekly=workingWeekRanges(month).map(range=>({...range,cents:rows.filter(e=>{const day=Number(e.date.slice(-2));return day>=range.start&&day<=range.end;}).reduce((sum,e)=>sum+e.cents,0)}));$('#weeks').innerHTML=weekly.map(({start,end,cents},i)=>`<div class="week"><div><span>Semana ${i+1} · dias ${start}–${end}</span><strong>${money(cents)}</strong></div><div class="track"><span style="width:${sales?cents/sales*100:0}%;background:var(--text)"></span></div><small>Participação no mês · ${sales?num(cents/sales*100):0}%${month===currentMonth&&Number(today.slice(-2))>=start&&Number(today.slice(-2))<=end?' · em andamento':''}</small></div>`).join('');
  const remaining=remainingWorkdays(month);$('#k-gap').textContent=hasGoal?money(Math.max(0,goal-sales)):'—';$('#gauge-meta').textContent=hasGoal?money(goal):'—';$('#remaining-days').textContent=remaining?remaining+' dias úteis restantes':'';$('#remaining-days').hidden=!remaining;$('#required-day-row').hidden=!remaining||!hasGoal;$('#required-day').textContent=hasGoal&&remaining?money(Math.ceil(Math.max(0,goal-sales)/remaining)):'—';$('#pieces-context').textContent=num(pieces)+' peças';$('#sales-progress').style.width=(hasGoal?Math.max(0,Math.min(100,percent)):0)+'%';$('#sales-progress').style.background=status.color;$('#orders-context').innerHTML=`<i class="dot" style="background:${status.color}"></i>${status.label} · ${hasGoal?num(percent)+'% da meta · ':''}${num(orders)} atendimentos`;all('[data-status-band]').forEach(el=>el.classList.toggle('active-band',el.dataset.statusBand===status.key));
  chart(rows,month,status,hasGoal?goal:0);renderHistory(rows);renderGoals();$('#storage-status').textContent=demo?'Exemplo · não salvo':ready?'Salvamento local ativo':'Armazenamento indisponível';$('#demo').textContent=demo?'Voltar aos meus dados':'Ver exemplo';$('#footer-mode').textContent=demo?'Dados fictícios · modo de exemplo':'Beta local · sem envio de dados ao servidor';$('#backup-count').textContent=`${db.entries.length} lançamento(s) e ${db.goals.length} meta(s), ${adminState().stores.length} loja(s) e ${adminState().users.length} usuário(s) e ${adminState().sellerGoals.length} meta(s) individual(is) mensal(is) e ${adminState().sellerDailyGoals.length} meta(s) diária(s) no backup.`;renderAdmin();renderOperation();renderEvolution();renderSellerGoals();renderCloudUI();redesignSync();animateIndicators();
 }
 function chart(rows,month,status,target=0){const weeklyTotal=rows.filter(e=>e.periodStart).reduce((a,e)=>a+e.cents,0);rows=rows.filter(e=>!e.periodStart);
  $('#chart-label').textContent=rows.length?'Vendas acumuladas':'Sem dados';const days=new Date(Number(month.slice(0,4)),Number(month.slice(-2)),0).getDate(),daily=Array(days).fill(0);rows.forEach(e=>daily[Number(e.date.slice(-2))-1]+=e.cents);let sum=0;const values=daily.map(v=>(sum+=v));const w=Math.max(240,$('#chart').clientWidth-36),h=230,left=65,right=20,top=20,bottom=35,max=Math.max(100,target,...values)*1.12,x=i=>left+i*(w-left-right)/(days-1),y=v=>h-bottom-v/max*(h-top-bottom),points=values.slice(0,month===currentMonth?Number(today.slice(-2)):month>currentMonth?0:days).map((v,i)=>`${x(i)},${y(v)}`).join(' '),color='var(--text)';
  $('#chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="group" aria-label="Vendas acumuladas por dia"><defs><linearGradient id="beta-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${color}" stop-opacity=".07"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${[0,.5,1].map(t=>`<line x1="${left}" x2="${w-right}" y1="${y(max*t)}" y2="${y(max*t)}" stroke="#E5E7EB" stroke-dasharray="3 5"/><text x="${left-7}" y="${y(max*t)+4}" text-anchor="end">${num(Math.round(max*t/100))}</text>`).join('')}<text x="${left}" y="12">R$</text><polygon points="${left},${h-bottom} ${points} ${x(month===currentMonth?Number(today.slice(-2))-1:days-1)},${h-bottom}" fill="url(#beta-fill)"/>${target?`<line x1="${x(0)}" y1="${y(0)}" x2="${x(days-1)}" y2="${y(target)}" stroke="var(--brand)" stroke-width="2" stroke-dasharray="6 5"/>`:''}<polyline class="chart-line" points="${points}" fill="none" stroke="${color}" stroke-width="2.5"/>${[0,6,13,20,days-1].map(i=>`<text x="${x(i)}" y="${h-10}" text-anchor="middle">${String(i+1).padStart(2,'0')}</text>`).join('')}${daily.map((v,i)=>{const day=new Date(Number(month.slice(0,4)),Number(month.slice(-2))-1,i+1),valid=day.getDay()!==0&&(month<currentMonth||month===currentMonth&&i+1<=Number(today.slice(-2)));return valid&&(v||rows.some(e=>Number(e.date.slice(-2))===i+1))?`<g class="chart-point" tabindex="0" role="button" data-chart-point data-day="${i}" aria-label="Dia ${i+1}, vendas ${money(v)}, acumulado ${money(values[i])}"><circle class="point-ring" cx="${x(i)}" cy="${y(values[i])}" r="10" fill="transparent"/><circle cx="${x(i)}" cy="${y(values[i])}" r="4" fill="${color}" stroke="#FFFFFF"/></g>`:''}).join('')}</svg>`;
  $('#chart-detail').textContent=weeklyTotal?'Gráfico diário: totais semanais ('+money(weeklyTotal)+') aparecem em Resultados por semana, sem distribuição diária.':rows.length?'Passe o mouse, toque ou use Tab nos pontos para ver os valores.':'Os resultados aparecerão após o primeiro lançamento.';
  const host=$('#chart'),svg=host.querySelector('svg'),tip=document.createElement('div');
  tip.className='sales-tooltip';tip.id='sales-tooltip';tip.setAttribute('role','tooltip');tip.hidden=true;host.append(tip);
  let pinned=false;const hide=()=>{if(pinned)return;tip.hidden=true;svg.classList.remove('has-highlight');svg.querySelectorAll('[data-chart-point]').forEach(p=>p.removeAttribute('data-active'));};host.onchartunpin=()=>{pinned=false;hide();};host.onpointerdown=event=>{if(!event.target.closest('[data-chart-point]')){pinned=false;hide();}};
  const reveal=i=>{
   const date=new Date(Number(month.slice(0,4)),Number(month.slice(-2))-1,i+1);if(!rows.length||date.getDay()===0||(month===currentMonth&&i+1>Number(today.slice(-2)))||month>currentMonth){tip.hidden=true;svg.classList.remove('has-highlight');svg.querySelectorAll('[data-chart-point]').forEach(p=>p.removeAttribute('data-active'));return;}
   svg.classList.add('has-highlight');svg.querySelectorAll('[data-chart-point]').forEach(p=>p.dataset.active=p.dataset.day===String(i));
   setChartTooltip(tip,date.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'}),money(values[i]),'Vendas do dia: '+money(daily[i]));tip.hidden=false;
   const point=new DOMPoint(x(i),y(values[i])).matrixTransform(svg.getScreenCTM()),box=host.getBoundingClientRect();
   tip.style.left=Math.max(8,Math.min(host.clientWidth-tip.offsetWidth-8,point.x-box.left-tip.offsetWidth/2))+'px';
   tip.style.top=Math.max(0,point.y-box.top-tip.offsetHeight-14)+'px';
   $('#chart-detail').textContent=`Dia ${i+1}, vendas ${money(daily[i])}, acumulado ${money(values[i])}`;
  };
  svg.onpointermove=e=>{if(e.pointerType==='touch'||pinned)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());if(p.x<left||p.x>w-right||p.y<top||p.y>h-bottom){hide();return;}reveal(Math.max(0,Math.min(days-1,Math.round((p.x-left)/(w-left-right)*(days-1)))));};
  host.onpointerleave=()=>{if(!pinned&&!host.contains(document.activeElement))hide();};
  all('[data-day]').forEach(el=>{const detail=()=>reveal(Number(el.dataset.day));el.setAttribute('aria-describedby',tip.id);el.addEventListener('pointerenter',detail);el.addEventListener('focus',detail);el.addEventListener('blur',()=>{if(!pinned)hide();});el.addEventListener('click',()=>{pinned=true;detail();});el.addEventListener('keydown',e=>{if(e.key==='Escape'){pinned=false;hide();}else if(e.key==='Enter'||e.key===' '){e.preventDefault();pinned=true;detail();}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const points=all('[data-chart-point]'),index=points.indexOf(el),next=points[Math.max(0,Math.min(points.length-1,index+(e.key==='ArrowRight'?1:-1)))];next?.focus();}});});
  host.onkeydown=e=>{if(e.key==='Escape'){pinned=false;hide();}};const lastPoint=host.querySelector('[data-day]:last-of-type');if(lastPoint)reveal(Number(lastPoint.dataset.day));

 }
 function renderHistory(rows){const query=$('#history-search').value.trim().toLocaleLowerCase('pt-BR');$('#history-count').textContent='('+rows.length+')';rows=rows.filter(e=>(e.seller+' '+e.store).toLocaleLowerCase('pt-BR').includes(query));const sorted=[...rows].sort((a,b)=>b.date.localeCompare(a.date)||a.seller.localeCompare(b.seller)),pages=Math.max(1,Math.ceil(sorted.length/8));page=Math.min(page,pages-1);$('#history').innerHTML=sorted.slice(page*8,page*8+8).map(e=>`<div class="history-row${e.id===recentlySavedId?' is-new':''}" data-history-date="${e.periodStart||e.date}" data-history-kind="${e.periodStart?'weekly':'daily'}" data-updated="${esc(e.updatedAt||'')}"><div><strong>${esc(e.seller)}</strong><b class="history-value">${money(e.cents)}</b><small>${e.periodStart?'Semanal · '+e.periodStart.split('-').reverse().join('/')+' a ':'Diário · '}${e.date.split('-').reverse().join('/')} · ${esc(e.store)}</small><small>${e.orders} atendimentos · ${e.pieces} peças</small></div><div class="history-actions"><button data-edit="${e.id}">${e.periodStart?'Atualizar':'Editar'}</button><button data-delete="${e.id}">Excluir</button></div></div>`).join('')||'<p>Nenhum lançamento neste período.</p>';$('#page-count').textContent=`Página ${page+1} de ${pages}`;$('#previous').disabled=page===0;$('#next').disabled=page>=pages-1;}
 function renderGoals(){$('#goals-list').innerHTML=data().goals.filter(g=>g.month===$('#month').value).map(g=>`<div class="goal-row"><div><strong>${esc(g.store)}</strong><small>${money(g.cents)} · ${g.month}</small></div><button data-goal="${esc(g.store)}">Editar</button></div>`).join('')||'<p>Nenhuma meta para este mês.</p>';}
 async function save(next,action='Atualizou dados'){if(demo)throw Error('Você está no exemplo. Volte aos seus dados para salvar.');if(!ready)throw Error('Armazenamento indisponível. Recarregue a página e confira as permissões do navegador.');if(busy)throw Error('Aguarde o salvamento em andamento.');next=validateDB(next);next.admin.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),actor:'Operador local',action});next.admin.audit=next.admin.audit.slice(-200);validateDB(next);busy=true;try{const result=await request('save',{revision,data:next});acceptCloud(result);$('#saved-at').textContent='Confirmado no Supabase às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});render();}finally{busy=false;}}
 function entryPeriodFields(){if(!$('#entry-month').value)$('#entry-month').value=$('#month').value||today.slice(0,7);const weekly=$('#entry-kind').value==='weekly';$('#entry-date-label').hidden=weekly;$('#entry-date').required=!weekly;for(const id of ['month','week']){$('#entry-'+id+'-label').hidden=!weekly;$('#entry-'+id).required=weekly;}const chosen=$('#entry-week').value,month=$('#entry-month').value||today.slice(0,7);$('#entry-week').innerHTML=workingWeekRanges(month).map(r=>`<option value="${r.start}|${r.end}">Dias ${r.start}–${r.end} · ${r.workingDays} dias úteis</option>`).join('');if([...$('#entry-week').options].some(x=>x.value===chosen))$('#entry-week').value=chosen;}
 $('#entry-kind').onchange=entryPeriodFields;$('#entry-month').onchange=entryPeriodFields;
 function resetEntry(){$('#entry-form').reset();$('#entry-id').value='';$('#entry-date').value=today;$('#entry-month').value=$('#month').value||today.slice(0,7);entryPeriodFields();$('#entry-title').textContent='Novo lançamento';$('#cancel-edit').hidden=true;$('#entry-error').textContent='';syncEntrySellers();}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)show(b.dataset.view);if(b.dataset.edit){const r=data().entries.find(x=>x.id===b.dataset.edit);if(!r)return;$('#entry-id').value=r.id;$('#entry-date').value=r.date;$('#entry-kind').value=r.periodStart?'weekly':'daily';$('#entry-month').value=r.date.slice(0,7);entryPeriodFields();if(r.periodStart)$('#entry-week').value=Number(r.periodStart.slice(-2))+'|'+Number(r.date.slice(-2));$('#entry-store').value=r.store;syncEntrySellers(r.seller);$('#entry-sales').value=amountInput(r.cents);$('#entry-orders').value=r.orders;$('#entry-pieces').value=r.pieces;$('#entry-title').textContent='Editar lançamento';$('#cancel-edit').hidden=false;$('#entry-date').focus();}if(b.dataset.delete){const r=data().entries.find(x=>x.id===b.dataset.delete);$('#confirm-text').textContent=`${r.seller} · ${money(r.cents)} · ${r.periodStart?'Semanal · '+r.periodStart.split('-').reverse().join('/')+' a ': 'Diário · '}${r.date.split('-').reverse().join('/')}. Esta ação exclui o lançamento do banco e registra a alteração no histórico.`;confirmAction=async()=>{const next=clone();next.entries=next.entries.filter(x=>x.id!==r.id);await save(next,'Excluiu resultado de '+r.seller);notify('Lançamento excluído.');};$('#confirm-dialog').showModal();}if(b.dataset.goal){goalMode='store';redesignSync();const g=data().goals.find(x=>x.month===$('#month').value&&x.store===b.dataset.goal);$('#goal-month').value=g.month;$('#goal-store').value=g.store;$('#goal-value').value=amountInput(g.cents);$('#goal-value').focus();}});
 $('#confirm-no').onclick=()=>$('#confirm-dialog').close();$('#confirm-yes').onclick=async()=>{try{await confirmAction();$('#confirm-dialog').close();}catch(e){$('#confirm-dialog').close();notice(e.message);}};
 $('#new-entry').onclick=()=>{show('records');resetEntry();$('#entry-date').focus();};$('#cancel-edit').onclick=resetEntry;
 $('#entry-form').onsubmit=async e=>{e.preventDefault();$('#entry-error').textContent='';try{const next=clone(),registry=adminState(),id=$('#entry-id').value||crypto.randomUUID(),store=canonical($('#entry-store').value,[...next.entries,...next.goals].map(x=>x.store).concat(registry.stores.map(x=>x.name))),seller=canonical($('#entry-seller').value,next.entries.filter(x=>same(x.store,store)).map(x=>x.seller).concat(registry.sellers.filter(x=>registry.stores.some(t=>t.id===x.storeId&&same(t.name,store))).map(x=>x.name))),record={id,updatedAt:new Date().toISOString(),date:$('#entry-date').value,store,seller,cents:amount($('#entry-sales').value),orders:Number($('#entry-orders').value),pieces:Number($('#entry-pieces').value)};if($('#entry-kind').value==='weekly'){const [start,end]=$('#entry-week').value.split('|').map(Number),month=$('#entry-month').value;record.periodStart=month+'-'+String(start).padStart(2,'0');record.date=month+'-'+String(end).padStart(2,'0');}if(!$('#entry-id').value){const a=adminState(),st=a.stores.find(x=>same(x.name,record.store));if(st&&!st.active)throw Error('Esta loja está arquivada. Reative o cadastro na Administração.');if(st&&a.sellers.some(x=>x.storeId===st.id&&same(x.name,record.seller)&&!x.active))throw Error('Este vendedor está arquivado. Reative o cadastro na Administração.');}if(!entrySellerChoices(validateDB(data()).admin,record.store,next.entries.find(e=>e.id===$('#entry-id').value&&same(e.store,record.store))?.seller||'').includes(record.seller))throw Error('Selecione um vendedor vinculado à loja escolhida.');if((record.periodStart||record.date)>today)throw Error('O lançamento não pode ter uma data futura.');if(record.orders===0&&(record.cents>0||record.pieces>0))throw Error('Informe ao menos um atendimento para vendas ou peças registradas.');if(next.entries.some(x=>x.id!==id&&(x.periodStart||x.date)<=record.date&&(record.periodStart||record.date)<=x.date&&same(x.store,store)&&same(x.seller,seller)))throw Error('Já existe um lançamento diário ou semanal deste vendedor no período. Edite o registro existente para evitar duplicidade.');const index=next.entries.findIndex(x=>x.id===id);if(index<0)next.entries.push(record);else next.entries[index]=record;await save(next,(index<0?'Registrou':'Editou')+' resultado de '+record.seller);recentlySavedId=index<0?id:'';$('#month').value=record.date.slice(0,7);$('#store').value=record.store;page=0;render();resetEntry();notify('Lançamento salvo. Indicadores atualizados.');if(recentlySavedId)setTimeout(()=>{recentlySavedId='';},2100);}catch(error){$('#entry-error').textContent=error.message;}};
 $('#goal-form').onsubmit=async e=>{e.preventDefault();$('#goal-error').textContent='';try{const next=clone(),registry=adminState(),g={month:$('#goal-month').value,store:canonical($('#goal-store').value,[...next.entries,...next.goals].map(x=>x.store).concat(registry.stores.map(x=>x.name))),cents:amount($('#goal-value').value)};if(adminState().stores.some(x=>same(x.name,g.store)&&!x.active))throw Error('Esta loja está arquivada. Reative o cadastro na Administração.');if(g.cents<=0)throw Error('A meta deve ser maior que zero.');const index=next.goals.findIndex(x=>x.month===g.month&&same(x.store,g.store));if(index<0)next.goals.push(g);else next.goals[index]=g;await save(next,(index<0?'Cadastrou':'Editou')+' meta de '+g.store);$('#month').value=g.month;render();notify('Meta salva. Indicadores atualizados.');}catch(error){$('#goal-error').textContent=error.message;}};
 $('#month').value=currentMonth;$('#goal-month').value=currentMonth;$('#month').onchange=()=>{if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test($('#month').value))$('#month').value=currentMonth;page=0;animationIntent=true;render();};$('#store').onchange=()=>{page=0;animationIntent=true;render();};$('#previous').onclick=()=>{page--;renderHistory(filtered());};$('#next').onclick=()=>{page++;renderHistory(filtered());};
 $('#demo').onclick=()=>{demo=!demo;animationIntent=true;$('#month').value=currentMonth;$('#store').value='';page=0;resetEntry();render();notify(demo?'Explorando dados fictícios. Seus dados permanecem guardados.':'De volta aos seus dados.');};
 $('#export').onclick=async()=>{try{if(demo)throw Error('Saia do exemplo para exportar seus dados.');acceptCloud(await request('export'));render();notify('Backup preparado. Confira o arquivo na pasta de downloads.');}catch(e){notice(e.message);}};
 $('#restore-file').onchange=async e=>{pendingRestore=null;$('#restore-preview').hidden=true;$('#restore-error').textContent='';try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Arquivo maior que o limite de 2 MB.');pendingRestore=validateDB(JSON.parse(await file.text()));$('#restore-summary').textContent=`Este backup contém ${pendingRestore.entries.length} lançamento(s) e ${pendingRestore.goals.length} meta(s), ${pendingRestore.admin.stores.length} loja(s), ${pendingRestore.admin.sellers.length} vendedor(es) e ${pendingRestore.admin.users.length} usuário(s) e ${pendingRestore.admin.sellerGoals.length} meta(s) individual(is) mensal(is) e ${pendingRestore.admin.sellerDailyGoals.length} meta(s) diária(s). Os cadastros administrativos também serão substituídos. Ao confirmar, os ${db.entries.length} lançamento(s) e ${db.goals.length} meta(s) atuais serão substituídos. Baixe um backup antes se quiser preservá-los.`;$('#restore-preview').hidden=false;}catch(error){$('#restore-error').textContent=error instanceof SyntaxError?'O arquivo não contém JSON válido.':error.message;}};
 $('#restore-cancel').onclick=()=>{pendingRestore=null;$('#restore-preview').hidden=true;$('#restore-file').value='';};$('#restore-confirm').onclick=async()=>{try{throw Error('A restauração local está desativada no modo online. Seus backups continuam preservados.');if(!pendingRestore)return;await save(pendingRestore,'Restaurou backup');$('#restore-cancel').click();resetEntry();notify('Backup restaurado e salvo neste navegador.');}catch(e){$('#restore-error').textContent=e.message;}};
 // Handle local forms without requesting sandbox form-navigation privileges.
 for(const id of ['#entry-form','#goal-form']){const form=$(id);const submit=e=>{e.preventDefault();if(form.reportValidity())form.onsubmit(e);};form.querySelector('button[type=submit]').addEventListener('click',submit);form.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT')submit(e);});}
 let chartWidth=0;new ResizeObserver(()=>{const width=$('#chart').clientWidth;if(width>0&&width!==chartWidth){chartWidth=width;render();}}).observe($('#chart'));
 // CLOUD_MODULE
 // ADMIN_MODULE
 // EVOLUTION_MODULE

  let pendingGoalImport = null;
  const goalImportScope = () => cloudProfile?.role === 'manager' ? cloudProfile.storeId : null;
  function clearGoalImport() {
    pendingGoalImport = null;
    $('#goal-import-file').value = '';
    $('#goal-import-preview').hidden = true;
    $('#goal-import-confirm').disabled = false;
  }
  $('#goal-import').onclick = () => {
    $('#goal-transfer-error').textContent = '';
    $('#goal-import-file').click();
  };
  $('#goal-export').onclick = async () => {
    $('#goal-transfer-error').textContent = '';
    try {
      if (demo) throw Error('Saia do exemplo para exportar suas metas.');
      if (!ready) throw Error('Aguarde o carregamento dos dados.');
      const csv = GoalTransfer.exportCsv(validateDB(clone()));
      await request('download-goals', {csv});
      notify('Metas exportadas em CSV.');
    } catch (error) {
      $('#goal-transfer-error').textContent = error.message;
    }
  };
  $('#goal-import-file').onchange = async event => {
    const file = event.target.files[0];
    clearGoalImport();
    $('#goal-transfer-error').textContent = '';
    if (!file) return;
    try {
      if (demo) throw Error('Saia do exemplo para importar metas.');
      if (!ready) throw Error('Aguarde o carregamento dos dados.');
      if (!/\.csv$/i.test(file.name)) throw Error('Selecione um arquivo CSV.');
      if (file.size > 2000000) throw Error('O CSV deve ter no máximo 2 MB.');
      const csv = await file.text();
      const result = GoalTransfer.prepareImport(csv, validateDB(clone()), goalImportScope());
      validateDB(result.next);
      pendingGoalImport = {csv, revision};
      const stats = result.stats;
      $('#goal-import-summary').textContent = 'Arquivo com ' + stats.total + ' meta(s): ' + stats.created + ' nova(s), ' + stats.updated + ' atualizada(s) e ' + stats.unchanged + ' sem alteração. Metas fora do arquivo serão preservadas.';
      $('#goal-import-confirm').disabled = stats.created + stats.updated === 0;
      $('#goal-import-preview').hidden = false;
    } catch (error) {
      $('#goal-transfer-error').textContent = error.message;
    }
  };
  $('#goal-import-cancel').onclick = clearGoalImport;
  $('#goal-import-confirm').onclick = async () => {
    $('#goal-transfer-error').textContent = '';
    try {
      if (!pendingGoalImport) throw Error('Selecione um CSV antes de importar.');
      if (pendingGoalImport.revision !== revision) throw Error('Os dados mudaram. Selecione o CSV novamente antes de confirmar.');
      const result = GoalTransfer.prepareImport(pendingGoalImport.csv, validateDB(clone()), goalImportScope());
      validateDB(result.next);
      $('#goal-import-confirm').disabled = true;
      await save(result.next, 'Importou ' + result.stats.total + ' metas via CSV');
      clearGoalImport();
      notify('Metas importadas e salvas.');
    } catch (error) {
      $('#goal-transfer-error').textContent = error.message;
      if (pendingGoalImport) $('#goal-import-confirm').disabled = false;
    }
  };
 resetEntry();render();show('dashboard');request('read').then(result=>{acceptCloud(result);ready=true;animationIntent=true;render();root.dispatchEvent(new CustomEvent('gi-data-ready',{detail:{success:true}}));if(!demo&&cloudProfile.role==='seller')show('evolution');}).catch(e=>{if(!demo)notice(e.message);render();root.dispatchEvent(new CustomEvent('gi-data-ready',{detail:{success:demo}}));});
})();
