function evoData(){const d=validateDB(data());if(demo)d.admin.sellerGoals=d.admin.sellers.map((s,i)=>({sellerId:s.id,month:currentMonth,cents:[4500000,4300000,4000000][i]||4000000}));return d;}
function evoRows(d,seller,store){return d.entries.filter(e=>(!store||same(e.store,store))&&(!seller||(same(e.seller,seller.name)&&d.admin.stores.some(s=>s.id===seller.storeId&&same(s.name,e.store)))));}
function evoCompare(value,old,format){const delta=evolutionDelta(value,old);return delta===null?'Sem base de comparação anterior':`${delta>0?'+':''}${num(delta)}% · anterior ${format(old)}`;}
function renderEvolution(){
 const d=evoData(),month=$('#month').value,store=$('#store').value,individual=$('#evo-mode').value==='individual',selected=$('#evo-seller').value;
 const people=d.admin.sellers.filter(s=>!store||d.admin.stores.some(t=>t.id===s.storeId&&same(t.name,store)));
 $('#evo-seller').innerHTML=(individual?'':'<option value="">Toda a equipe</option>')+people.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(d.admin.stores.find(t=>t.id===s.storeId)?.name||'')}</option>`).join('');
 $('#evo-seller').value=people.some(s=>s.id===selected)?selected:(individual?people[0]?.id||'':'');
 const seller=people.find(s=>s.id===$('#evo-seller').value),period=evolutionPeriod(month,today),allRows=evoRows(d,seller,store);
 const rows=allRows.filter(e=>e.date.startsWith(month)&&Number(e.date.slice(-2))<=period.cutoff&&e.date<=today),previous=allRows.filter(e=>e.date.startsWith(period.previous)&&Number(e.date.slice(-2))<=period.previousCutoff);
 const t=evolutionTotals(rows),old=evolutionTotals(previous),tm=t.orders?t.sales/t.orders:0,oldTm=old.orders?old.sales/old.orders:0,pa=t.orders?t.pieces/t.orders:0,oldPa=old.orders?old.pieces/old.orders:0;
 $('#evo-context').textContent=seller?`${seller.name} · ${d.admin.stores.find(x=>x.id===seller.storeId)?.name||''} · somente consulta`:'Acompanhamento da equipe da loja selecionada. Selecione um vendedor para ver o detalhe.';
 if(view==='evolution'){$('#page-title').textContent=individual?'Minha evolução':'Evolução da equipe';$('#page-sub').textContent=individual?'Acompanhe seus resultados registrados pelo gestor.':'Compare resultados e acompanhe cada vendedor.';}
 renderGreeting();
 $('#evo-empty').hidden=rows.length>0&&!period.future;$('#evo-empty').textContent=period.future?'Período futuro: ainda não há resultados realizados.':individual&&!seller?'Cadastre um vendedor na Administração para visualizar sua evolução.':'Nenhum lançamento neste período. Os resultados aparecerão quando o gestor registrar as vendas.';
 $('#evo-content').hidden=period.future||(individual&&!seller);if($('#evo-content').hidden)return;
 const individualGoal=seller?d.admin.sellerGoals.find(g=>g.month===month&&g.sellerId===seller.id):null;
 const stores=d.admin.stores.filter(s=>!store||same(s.name,store)),storeGoals=d.goals.filter(g=>g.month===month&&(!store||same(g.store,store)));
 const goal=seller?individualGoal?.cents||0:storeGoals.reduce((a,g)=>a+g.cents,0),covered=seller?!!individualGoal:stores.length>0&&stores.every(s=>storeGoals.some(g=>same(s.name,g.store))),pct=covered&&goal?t.sales/goal*100:null;
 $('#evo-stats').innerHTML=[['Vendas no período',money(t.sales),evoCompare(t.sales,old.sales,money)],['Atingimento da meta',pct===null?'—':num(pct)+'%',seller?'Meta individual mensal':'Metas mensais das lojas'],['Ticket médio',t.orders?money(Math.round(tm)):'—',t.orders&&old.orders?evoCompare(tm,oldTm,c=>money(Math.round(c))):'Sem base de comparação anterior'],['Peças por atendimento',t.orders?num(pa):'—',t.orders&&old.orders?evoCompare(pa,oldPa,num):'Sem base de comparação anterior']].map(([label,value,note])=>`<article class="card stat"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`).join('');
 $('#evo-goal-title').textContent=seller?'Meta individual mensal':'Meta mensal das lojas';$('#evo-goal-text').textContent=covered?money(goal):'Meta não definida';
 $('#evo-goal-detail').textContent=covered?(t.sales>=goal?'Acima da meta: '+money(t.sales-goal):'Falta para a meta: '+money(goal-t.sales)):'O gestor precisa cadastrar a meta para permitir a comparação.';
 const status=state(pct||0,month,covered,rows.length>0);$('#evo-goal-bar').style.width=(pct===null?0:Math.min(100,pct))+'%';$('#evo-goal-bar').style.background=status.color;
 const dates=rows.map(e=>e.updatedAt).filter(Boolean).sort();$('#evo-updated').textContent=dates.length?'Última atualização dos registros exibidos: '+new Date(dates[dates.length-1]).toLocaleString('pt-BR'):rows.length?'Registros antigos: horário de atualização indisponível.':'Ainda sem atualização de resultados.';
 $('#evo-comparison-note').textContent=month===currentMonth?`Comparação: dias 1–${period.cutoff} deste mês com dias 1–${period.previousCutoff} de ${period.previous}.`:`Comparação com o mês completo ${period.previous}.`;
 const visiblePeople=seller?[seller]:people;$('#evo-list-title').textContent=seller?'Resumo individual':'Resultados da equipe';
 const salesFor=s=>evolutionTotals(evoRows(d,s,store).filter(e=>e.date.startsWith(month)&&e.date<=today)).sales;
 const groups=d.admin.stores.map(st=>({store:st,sellers:visiblePeople.filter(s=>s.storeId===st.id).sort((a,b)=>salesFor(b)-salesFor(a)||a.name.localeCompare(b.name,'pt-BR'))})).filter(g=>g.sellers.length).sort((a,b)=>a.store.name.localeCompare(b.store.name,'pt-BR'));
 const sellerCard=(s,rank)=>{
  const st=d.admin.stores.find(x=>x.id===s.storeId),sr=evoRows(d,s,store).filter(e=>e.date.startsWith(month)&&e.date<=today),v=evolutionTotals(sr),g=d.admin.sellerGoals.find(x=>x.month===month&&x.sellerId===s.id),hasGoal=!!g&&g.cents>0,pct=hasGoal?v.sales/g.cents*100:null,status=state(pct||0,month,hasGoal,sr.length>0);
  const initials=s.name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();
  return `<article class="seller-card" aria-label="Resultados de ${esc(s.name)}"><div class="seller-card-head"><span class="seller-avatar" aria-hidden="true">${esc(initials)}</span><span class="seller-rank" aria-label="Posição ${rank} em vendas na loja">${rank}º</span><div><h3>${esc(s.name)}</h3><p>${esc(st?.name||'Loja não definida')}</p></div></div><div class="seller-sales"><span>Vendas no período</span><strong>${money(v.sales)}</strong></div><dl class="seller-metrics"><div><dt>Meta individual</dt><dd>${hasGoal?money(g.cents):'Não definida'}</dd></div><div><dt>Atingimento</dt><dd>${pct===null?'—':num(pct)+'%'}</dd></div><div><dt>Ticket médio · TM</dt><dd>${v.orders?money(Math.round(v.sales/v.orders)):'—'}</dd></div><div><dt>Peças por atendimento · PA</dt><dd>${v.orders?num(v.pieces/v.orders):'—'}</dd></div></dl><div class="seller-status"><span class="badge" style="background:${status.bg}"><i class="dot" style="background:${status.color}"></i>${status.label}</span><small>${num(v.orders)} atendimentos · ${num(v.pieces)} peças</small></div>${hasGoal?`<div class="track" role="img" aria-label="${num(pct)}% da meta individual"><span style="width:${Math.max(0,Math.min(100,pct))}%;background:${status.color}"></span></div>`:''}${seller?'':`<button data-evo-seller="${esc(s.id)}" aria-label="Ver evolução de ${esc(s.name)}">Ver evolução</button>`}</article>`;
 };
 $('#evo-results').innerHTML=groups.map((group,i)=>`<section class="seller-store-group" aria-labelledby="seller-store-${i}"><header class="seller-store-heading"><h3 id="seller-store-${i}">${esc(group.store.name)}</h3><p>Ranking por vendas no período · maior para menor</p></header><div class="seller-store-grid">${group.sellers.map((s,i)=>sellerCard(s,i+1)).join('')}</div></section>`).join('')||'<p>Nenhum vendedor cadastrado para esta loja.</p>';
 drawEvolution(allRows,month,'#059669');animateIndicators();
}
function drawEvolution(rows,month,color){
 const group=$('#evo-group').value,buckets=evolutionBuckets(rows,month,group,today),w=640,h=260,l=70,r=20,b=42,t=24,max=Math.max(100,...buckets.map(x=>x.sales)),x=i=>l+i*(w-l-r)/Math.max(1,buckets.length-1),y=v=>h-b-(v/max)*(h-b-t);
 $('#evo-chart-caption').textContent=group==='month'?'Últimos seis meses; o mês atual é parcial.':group==='week'?'Blocos de 7 dias úteis, sem contar domingos. O bloco atual é parcial.':'Valores do mês selecionado. Dias sem lançamento aparecem como zero.';
 $('#evo-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="group" aria-label="Evolução das vendas"><defs><linearGradient id="evo-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${color}" stop-opacity=".2"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><polygon points="${l},${h-b} ${buckets.map((p,i)=>`${x(i)},${y(p.sales)}`).join(' ')} ${x(buckets.length-1)},${h-b}" fill="url(#evo-fill)"/><line x1="${l}" y1="${h-b}" x2="${w-r}" y2="${h-b}" stroke="#E5E7EB"/>${[0,.5,1].map(k=>`<text x="${l-8}" y="${y(max*k)+4}" text-anchor="end">${num(Math.round(max*k/100))}</text>`).join('')}<text x="${l}" y="14">R$</text><polyline points="${buckets.map((p,i)=>`${x(i)},${y(p.sales)}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3"/>${buckets.map((p,i)=>`<g tabindex="0" role="button" data-evo-point="${i}" aria-label="${esc(p.label)}: ${money(p.sales)}"><circle cx="${x(i)}" cy="${y(p.sales)}" r="10" fill="transparent"/><circle cx="${x(i)}" cy="${y(p.sales)}" r="4" fill="${color}" stroke="#FFFFFF"/></g>${buckets.length<9||i%7===0||i===buckets.length-1?`<text x="${x(i)}" y="${h-14}" text-anchor="middle">${p.label}</text>`:''}`).join('')}</svg>`;
 $('#evo-chart-detail').textContent='Toque, passe o mouse ou use Tab nos pontos para consultar os valores.';
 const host=$('#evo-chart'),svg=host.querySelector('svg'),tip=document.createElement('div');tip.className='sales-tooltip';tip.id='evo-tooltip';tip.setAttribute('role','tooltip');tip.hidden=true;host.append(tip);
 const hide=()=>{tip.hidden=true;};
 const reveal=i=>{const point=buckets[i];if(!point)return;const period=group==='day'?'Dia ':group==='week'?'Dias ':'Mês ';tip.textContent=period+point.label+'\nVendas: '+money(point.sales);tip.hidden=false;
  const screen=new DOMPoint(x(i),y(point.sales)).matrixTransform(svg.getScreenCTM()),box=host.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(host.clientWidth-tip.offsetWidth-8,screen.x-box.left-tip.offsetWidth/2))+'px';tip.style.top=Math.max(0,screen.y-box.top-tip.offsetHeight-14)+'px';$('#evo-chart-detail').textContent=period+point.label+': '+money(point.sales);
 };
 svg.onpointermove=e=>{if(e.pointerType==='touch'||!buckets.length)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());if(point.x<l||point.x>w-r||point.y<t||point.y>h-b){hide();return;}reveal(Math.max(0,Math.min(buckets.length-1,Math.round((point.x-l)/(w-l-r)*(buckets.length-1)))));};host.onpointerleave=hide;
 all('[data-evo-point]').forEach(el=>{const detail=()=>reveal(Number(el.dataset.evoPoint));el.setAttribute('aria-describedby',tip.id);el.onclick=detail;el.onfocus=detail;el.onblur=hide;el.onpointerenter=detail;el.onkeydown=e=>{if(e.key==='Escape')hide();else if(e.key==='Enter'||e.key===' '){e.preventDefault();detail();}};});

}
function renderOperation(){
 const d=evoData(),month=$('#month').value,store=$('#store').value,stores=d.admin.stores.filter(s=>(s.active||d.entries.some(e=>same(e.store,s.name)&&e.date.startsWith(month)))&&(!store||same(s.name,store))),alerts=[];
 $('#operation-period').textContent=month<currentMonth?'Mês encerrado: resultados comparados às metas.':month===currentMonth?'Mês em andamento: confirme os lançamentos antes de avaliar o resultado.':'Período futuro: planeje as metas das lojas.';
 $('#operation-stores').innerHTML=stores.map(s=>{const rows=d.entries.filter(e=>same(e.store,s.name)&&e.date.startsWith(month)),v=evolutionTotals(rows),g=d.goals.find(x=>same(x.store,s.name)&&x.month===month),pct=g?v.sales/g.cents*100:null;if(!g)alerts.push({s,text:'Meta mensal não cadastrada',color:'#F59E0B'});if(!rows.length&&month<=currentMonth)alerts.push({s,text:'Sem lançamentos no mês selecionado',color:'#F59E0B'});if(g&&rows.length&&month<currentMonth&&v.sales<g.cents)alerts.push({s,text:'Mês encerrado abaixo da meta: '+num(pct)+'%',color:pct<50?'#EF4444':'#F59E0B'});return `<tr><td>${esc(s.name)}</td><td>${money(v.sales)}</td><td>${g?money(g.cents):'—'}</td><td>${pct===null?'—':num(pct)+'%'}</td><td>${v.orders?money(Math.round(v.sales/v.orders)):'—'}</td><td>${v.orders?num(v.pieces/v.orders):'—'}</td><td><button data-evo-store="${s.id}">Ver equipe</button></td></tr>`;}).join('')||'<tr><td colspan="7">Cadastre uma loja para acompanhar a operação.</td></tr>';
 $('#operation-alerts').innerHTML=alerts.map(a=>`<div class="operation-alert"><i class="dot" style="background:${a.color}"></i><span><strong>${esc(a.s.name)}</strong><br>${a.text}</span><button data-evo-store="${a.s.id}">Ver loja</button></div>`).join('')||(stores.length?'<p>Nenhum ponto de atenção identificado pelos critérios disponíveis.</p>':'<p>Aguardando o cadastro das lojas.</p>');
}
function renderSellerGoals(){
 const d=evoData(),a=d.admin,selected=$('#seller-goal-person').value;$('#seller-goal-person').innerHTML='<option value="">Selecione um vendedor</option>'+a.sellers.filter(s=>s.active&&a.stores.some(t=>t.id===s.storeId&&t.active)).map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(a.stores.find(t=>t.id===s.storeId).name)}</option>`).join('');$('#seller-goal-person').value=selected;
 $('#seller-goal-list').innerHTML=a.sellerGoals.filter(g=>g.month===$('#month').value&&a.sellers.some(s=>s.id===g.sellerId&&(!$('#store').value||a.stores.some(t=>t.id===s.storeId&&same(t.name,$('#store').value))))).map(g=>{const s=a.sellers.find(x=>x.id===g.sellerId),t=a.stores.find(x=>x.id===s.storeId);return `<div class="goal-row"><div><strong>${esc(s.name)}</strong><small>${esc(t.name)} · ${money(g.cents)}</small></div><button data-seller-goal="${s.id}">Editar</button></div>`;}).join('')||'<p>Nenhuma meta individual neste período.</p>';
}
$('#evo-mode').onchange=renderEvolution;$('#evo-seller').onchange=renderEvolution;$('#evo-group').onchange=renderEvolution;
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.evoStore){const s=evoData().admin.stores.find(s=>s.id===b.dataset.evoStore);$('#store').value=s.name;$('#evo-mode').value='team';$('#evo-seller').value='';render();show('evolution');}
 if(b.dataset.evoSeller){$('#evo-seller').value=b.dataset.evoSeller;renderEvolution();window.scrollTo(0,0);}
 if(b.dataset.sellerGoal){const d=evoData(),g=d.admin.sellerGoals.find(x=>x.sellerId===b.dataset.sellerGoal&&x.month===$('#month').value);$('#seller-goal-month').value=g.month;$('#seller-goal-person').value=g.sellerId;$('#seller-goal-value').value=amountInput(g.cents);$('#seller-goal-value').focus();}
});
$('#seller-goal-month').value=currentMonth;
$('#seller-goal-form').onsubmit=async e=>{e.preventDefault();$('#seller-goal-error').textContent='';try{const next=validateDB(clone()),seller=next.admin.sellers.find(s=>s.id===$('#seller-goal-person').value),month=$('#seller-goal-month').value,cents=amount($('#seller-goal-value').value);if(!seller||!seller.active||!next.admin.stores.some(s=>s.id===seller.storeId&&s.active))throw Error('Selecione um vendedor de uma loja ativa.');if(cents<=0)throw Error('A meta deve ser maior que zero.');const g={sellerId:seller.id,month,cents},i=next.admin.sellerGoals.findIndex(x=>x.sellerId===seller.id&&x.month===month);if(i<0)next.admin.sellerGoals.push(g);else next.admin.sellerGoals[i]=g;await save(next,`${i<0?'Cadastrou':'Editou'} meta individual de ${seller.name}`);$('#month').value=month;render();notify('Meta individual salva.');}catch(err){$('#seller-goal-error').textContent=err.message;}};
$('#seller-goal-form button[type=submit]').onclick=e=>{e.preventDefault();if($('#seller-goal-form').reportValidity())$('#seller-goal-form').onsubmit(e);};
$('#seller-goal-form').onkeydown=e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT'){e.preventDefault();if($('#seller-goal-form').reportValidity())$('#seller-goal-form').onsubmit(e);}};
