// Presentation only: reuse the existing forms and permission checks.
function entryPreview(){let cents=0;try{cents=amount($('#entry-sales').value);}catch{}const orders=Number($('#entry-orders').value),pieces=Number($('#entry-pieces').value);$('#entry-tm').textContent=orders>0?money(Math.round(cents/orders)):'—';$('#entry-pa').textContent=orders>0?num(pieces/orders):'—';}
function segmentControl(id){const select=$(id);if(!select)return;let group=select.parentElement.querySelector('[data-segment-source]');if(!group){group=document.createElement('div');group.className='segments';group.dataset.segmentSource=id;group.setAttribute('role','group');group.setAttribute('aria-label',select.parentElement.firstChild.textContent.trim());select.classList.add('segment-source');select.tabIndex=-1;select.setAttribute('aria-hidden','true');group.innerHTML=[...select.options].map(o=>`<button type="button" data-choice="${esc(o.value)}">${esc(o.textContent)}</button>`).join('');select.after(group);group.addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(!b)return;select.value=b.dataset.choice;select.dispatchEvent(new Event('change',{bubbles:true}));redesignSync();});}for(const b of group.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.choice===select.value));}
function goalProgress(list,goals,individual){const d=evoData();[...list.querySelectorAll('.goal-row')].forEach((row,i)=>{const g=goals[i];if(!g)return;const seller=individual?d.admin.sellers.find(s=>s.id===g.sellerId):null,store=individual?d.admin.stores.find(s=>s.id===seller?.storeId)?.name:g.store;const entries=d.entries.filter(e=>e.date.startsWith(g.month)&&same(e.store,store||'')&&(!individual||same(e.seller,seller.name)));const sales=entries.reduce((a,e)=>a+e.cents,0),pct=g.cents?sales/g.cents*100:null,s=state(pct,g.month,g.cents>0,entries.length>0);const extra=document.createElement('div');extra.className='goal-metrics';extra.innerHTML=`<span>Realizado ${money(sales)}</span>${statusChip(s)}<span>${pct===null?'—':num(pct)+'%'}</span><div class="track" style="width:100%"><span style="width:${Math.min(100,pct||0)}%;background:${s.color}"></span></div>`;row.firstElementChild.append(extra);});}
let goalMode='store';
function redesignSync(){
 const sections={dashboard:'VISÃO GERAL',evolution:'EVOLUÇÃO',records:'LANÇAMENTOS',targets:'METAS',admin:'ADMINISTRAÇÃO'};$('#page-eyebrow').textContent=(sections[view]||'PAINEL')+' / '+$('#month').value;
 $('#mobile-sales-gap').textContent='Faltam '+$('#gap-value').textContent;$('#demo').hidden=!cloudProfile||cloudProfile.role==='seller';for(const row of all('#team-body tr'))[...row.children].forEach((td,i)=>td.dataset.label=['Vendedor','Vendas','Atingimento','Status','TM','PA'][i]);
 for(const b of all('.rail [data-view]')){b.setAttribute('aria-label',b.textContent.trim());b.title=b.textContent.trim();}
 if(!$('#seller-goal-add')){const button=document.createElement('button');button.id='seller-goal-add';button.textContent='+ Meta individual';button.type='button';button.onclick=()=>{goalMode='seller';redesignSync();$('#seller-goal-person').focus();};$('#seller-goal-list').closest('article').append(button);}
 $('#profile-menu').textContent=cloudProfile?.name?.split(' ')[0]||'Perfil';$('#profile-panel [data-view=admin]').hidden=cloudProfile?.role!=='admin';root.querySelector('.rail [data-view=admin]').hidden=cloudProfile?.role!=='admin';
 for(const id of ['#entry-kind','#evo-group','#admin-role'])segmentControl(id);entryPreview();
 if(!$('#targets .targets-layout')){const layout=document.createElement('div');layout.className='targets-layout';const forms=document.createElement('div'),lists=document.createElement('div');forms.className='goal-forms';lists.className='goal-lists';for(const id of ['#goal-form','#seller-goal-form'])forms.append($(id));for(const id of ['#goals-list','#seller-goal-list'])lists.append($(id).closest('article'));layout.append(forms,lists);$('#targets').append(layout);for(const empty of all('#targets>.split'))empty.remove();}
 $('#goal-form').hidden=goalMode!=='store';$('#seller-goal-form').hidden=goalMode!=='seller';for(const b of all('[data-goal-mode]'))b.setAttribute('aria-pressed',String(b.dataset.goalMode===goalMode));
 const d=evoData(),month=$('#month').value;$('#goals-total').textContent='Meta total: '+money(d.goals.filter(g=>g.month===month).reduce((a,g)=>a+g.cents,0));
 if(!$('#goals-list .goal-metrics'))goalProgress($('#goals-list'),d.goals.filter(g=>g.month===month),false);
 if(!$('#seller-goal-list .goal-metrics'))goalProgress($('#seller-goal-list'),d.admin.sellerGoals.filter(g=>g.month===month&&d.admin.sellers.some(s=>s.id===g.sellerId&&(!$('#store').value||d.admin.stores.some(t=>t.id===s.storeId&&same(t.name,$('#store').value))))),true);
 for(const row of all('#history .history-row')){if(row.dataset.historyKind==='weekly'&&!row.querySelector('.weekly-chip')){const chip=document.createElement('span');chip.className='weekly-chip';chip.textContent='Semanal · acumulado';row.firstElementChild.append(chip);}if(row.dataset.updated&&Date.now()-Date.parse(row.dataset.updated)<8000&&!row.querySelector('.new-chip')){const chip=document.createElement('span');chip.className='new-chip';chip.textContent='Novo';row.firstElementChild.append(chip);setTimeout(()=>chip.remove(),8000);}const prev=row.previousElementSibling;if(prev?.classList.contains('history-group')||prev?.dataset.historyDate===row.dataset.historyDate)continue;const heading=document.createElement('p');heading.className='history-group';heading.textContent=(row.dataset.historyKind==='weekly'?'BLOCO SEMANAL / ':'DIA / ')+row.dataset.historyDate.split('-').reverse().join('/');row.before(heading);}
 const counts={stores:d.admin.stores.length,sellers:d.admin.sellers.length,users:cloudProfiles.length,backup:null,audit:d.admin.audit.length},names={stores:'Lojas',sellers:'Vendedores',users:'Usuários e perfis',backup:'Backup',audit:'Histórico'};for(const b of all('[data-admin-tab]'))b.textContent=names[b.dataset.adminTab]+(counts[b.dataset.adminTab]==null?'':' · '+counts[b.dataset.adminTab]);
 for(const row of all('.admin-row')){const block=row.firstElementChild;if(block&&!block.querySelector('.admin-avatar')){const avatar=document.createElement('span');avatar.className='admin-avatar';avatar.setAttribute('aria-hidden','true');avatar.textContent=(block.querySelector('strong')?.textContent||'').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const info=document.createElement('div');while(block.firstChild)info.append(block.firstChild);block.append(avatar,info);}}
}
$('#profile-menu').onclick=()=>{const panel=$('#profile-panel');panel.hidden=!panel.hidden;$('#profile-menu').setAttribute('aria-expanded',String(!panel.hidden));};
root.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.goalMode){goalMode=b.dataset.goalMode;redesignSync();}if(b?.dataset.view){$('#profile-panel').hidden=true;$('#profile-menu').setAttribute('aria-expanded','false');}queueMicrotask(redesignSync);});
$('#clear-entry').onclick=()=>{resetEntry();entryPreview();};$('#history-search').oninput=()=>{page=0;renderHistory(filtered());redesignSync();};$('#admin-search').addEventListener('input',()=>queueMicrotask(redesignSync));
for(const id of ['#entry-sales','#entry-orders','#entry-pieces'])$(id).addEventListener('input',entryPreview);
$('#goal-value').addEventListener('input',()=>{let v=0;try{v=amount($('#goal-value').value);}catch{}$('#weekly-suggestion-values').textContent=[25,33,24,18].map(p=>money(Math.round(v*p/100))).join(' · ');});

window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='gi-public-preview')return;demo=true;$('#notice').hidden=true;$('#demo').hidden=true;render();$('#demo').hidden=true;show('dashboard');});
