const {readFileSync}=require('node:fs');
const {runInNewContext}=require('node:vm');
const assert=require('node:assert/strict');
const source=readFileSync(require('node:path').join(__dirname,'../beta/beta-schema.js'),'utf8');
const validate=runInNewContext(source+';validateDB');
const copy=x=>JSON.parse(JSON.stringify(x));
const legacy={version:1,entries:[{id:'sale1',date:'2026-10-01',store:'Centro',seller:'Ana',cents:12345,orders:2,pieces:3}],goals:[{month:'2026-10',store:'Centro',cents:20000}]};
const migrated=copy(validate(legacy));
assert.deepEqual(migrated.entries,legacy.entries);assert.deepEqual(migrated.goals,legacy.goals);
assert.equal(migrated.admin.stores.length,1);assert.equal(migrated.admin.sellers.length,1);
assert.deepEqual(copy(validate(migrated)),migrated);
migrated.admin.users.push({id:'user1',name:'Ana',email:'ana@example.com',role:'seller',storeId:migrated.admin.stores[0].id,sellerId:migrated.admin.sellers[0].id,active:true});
migrated.admin.audit.push({id:'event1',at:'2026-10-04T12:00:00Z',actor:'Operador local',action:'Cadastrou usuário: Ana'});
assert.deepEqual(copy(validate(copy(migrated))),migrated,'backup retains administrative data');
const bad=copy(migrated);bad.admin.users[0].storeId='missing';assert.throws(()=>validate(bad));
const duplicate=copy(migrated);duplicate.admin.stores.push({id:'other',name:'centro',active:true});assert.throws(()=>validate(duplicate));
const duplicateEmail=copy(migrated);duplicateEmail.admin.users.push({...duplicateEmail.admin.users[0],id:'user2',email:'ANA@example.com'});assert.throws(()=>validate(duplicateEmail));
const archived=copy(migrated);archived.admin.stores[0].active=false;assert.equal(validate(archived).admin.stores[0].active,false);
const invalid=copy(migrated);invalid.admin.audit[0].at='not a date';assert.throws(()=>validate(invalid));
console.log('Schema: migration, roundtrip, references, duplicates, archive and audit validation passed.');
